### ISSUE TITLE
Error in SMTP transport

### ISSUE THREAD

**Issue by two8eleven** [pucherot/Pi.Alert#243] opened 2023-12-02 21:18 UTC
I have configured SMTP but getting an error regarding the smtp_timeout. How can i configure this?

The error:

`Traceback (most recent call last):
  File "/home/pi/pialert/front/plugins/_publisher_email/email_smtp.py", line 199, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/pi/pialert/front/plugins/_publisher_email/email_smtp.py", line 60, in main
    result = send(notification["HTML"], notification["Text"])    
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pi/pialert/front/plugins/_publisher_email/email_smtp.py", line 117, in send
    send_email(msg)
  File "/home/pi/pialert/front/plugins/_publisher_email/email_smtp.py", line 144, in send_email
    smtp_connection = smtplib.SMTP_SSL(get_setting_value('SMTP_SERVER'), get_setting_value('SMTP_PORT'), timeout=smtp_timeout)
                                                                                                                 ^^^^^^^^^^^^
NameError: name 'smtp_timeout' is not defined`

**Comment by jokob-sk** [comment] 2023-12-02 21:26
Hi, could you please close this issue and contribute to the correct fork? Thanks!

Also, this seems to be a duplicate of this one:

https://github.com/jokob-sk/Pi.Alert/issues/512

**Closed as completed** 2023-12-02 21:32 UTC
