### ISSUE TITLE
403 Forbidden

### ISSUE THREAD

**Issue by aund** [pucherot/Pi.Alert#53] opened 2021-01-27 14:30 UTC
Hello,

I'm receiving a "403 Forbidden" error when hitting the pi alert page.

I'm running pihole on a VM. I installed pi.alert using the one step install below

curl -sSL https://github.com/pucherot/Pi.Alert/raw/main/install/pialert_install.sh | bash

I added an entry for pi.alert into the hosts file on the server for DNS resolution and virtual host match up in lighttpd

The main pihole v5.2.4  web interface is loading fine using http://pi.hole

Here are  the various permissions on the directories:
drwxr-xr-x 2 root     root     4096 Dec 18 15:32 pihole
lrwxrwxrwx 1 root     root       19 Jan 27 13:23 pialert -> /root/pialert/front
drwxrwxrwx 9 root root 4096 Jan 25 21:41 pialert

Here is the log from lighttpd:

1611757158|192.168.0.195|GET /admin/api.php?summaryRaw&getQuerySources&topClientsBlocked HTTP/1.1|200|1397
1611757171|pi.alert|GET / HTTP/1.1|403|341
1611757171|pi.alert|GET /favicon.ico HTTP/1.1|403|341

Thanks

**Comment by pucherot** [comment] 2021-01-27 14:37
You have install Pi.Alert in the "**root**" user. I think is better use "**pi**" user.

please, execute this command:
`ls -l /var/www/html`

**Comment by KifKick** [comment] 2021-01-27 17:09
I have same issue like @aund. I'm hosting my pi-hole service as a VM on debian and got that 403 Forbidden error after running install script. I'm using root user for pi-hole.

**Comment by pucherot** [comment] 2021-01-27 18:15
> I have same issue like @aund. I'm hosting my pi-hole service as a VM on debian and got that 403 Forbidden error after running install script. I'm using root user for pi-hole.

please, execute this command:
`ls -l /var/www/html`

**Comment by KifKick** [comment] 2021-01-27 19:10
Fresh installation of pi-hole on debian 10 with pi-alert.
`root@pitest:~# ls -l /var/www/html`
`total 12`
`drwxr-xr-x 7 root root 4096 Jan 27 19:04 admin`
`-rw-r--r-- 1 root root 3388 Jan 27 19:04 index.lighttpd.orig`
`lrwxrwxrwx 1 root root   19 Jan 27 19:07 pialert -> /root/pialert/front`
`drwxr-xr-x 2 root root 4096 Jan 27 19:04 pihole`

**Comment by pucherot** [comment] 2021-01-27 19:42
and now:
`ls -l /root`
`ls -l /root/pialert`

**Comment by KifKick** [comment] 2021-01-27 19:49
First cmd
`root@pitest:~# ls -l /root`
`total 4`
`drwxrwxrwx 9 root root 4096 Jan 26 20:10 pialert`

Second one
`root@pitest:~# ls -l /root/pialert`
`total 72`
`-rwxrwxrwx 1 root root     35149 Jan 13 21:28 LICENSE.txt`
`-rwxrwxrwx 1 root root      4510 Jan 27 10:29 README.md`
`drwxrwxrwx 2 root root      4096 Jan 24 12:11 back`
`drwxrwxrwx 2 root root      4096 Jan 27 19:06 config`
`drwxrwx--- 2 root www-data  4096 Jan 27 19:45 db`
`drwxrwxrwx 3 root root      4096 Jan 27 15:13 docs`
`drwxrwxrwx 7 root root      4096 Jan 13 21:37 front`
`drwxrwxrwx 2 root root      4096 Jan 27 19:07 install`
`drwxrwxrwx 2 root root      4096 Jan 27 19:15 log`

**Comment by pucherot** [comment] 2021-01-27 20:56
please, execute this commands:
~~~
sudo chgrp -R www-data ~/pialert/front
chmod -R 770 ~/pialert/front
~~~

**Comment by KifKick** [comment] 2021-01-27 21:01
Still same result, 403 Forbidden

`root@pitest:~# ls -l /root/pialert`
`total 72`
`-rwxrwxrwx 1 root root     35149 Jan 13 21:28 LICENSE.txt`
`-rwxrwxrwx 1 root root      4510 Jan 27 10:29 README.md`
`drwxrwxrwx 2 root root      4096 Jan 24 12:11 back`
`drwxrwxrwx 2 root root      4096 Jan 27 19:06 config`
`drwxrwx--- 2 root www-data  4096 Jan 27 20:55 db`
`drwxrwxrwx 3 root root      4096 Jan 27 15:13 docs`
`drwxrwx--- 7 root www-data  4096 Jan 13 21:37 front`
`drwxrwxrwx 2 root root      4096 Jan 27 19:07 install`
`drwxrwxrwx 2 root root      4096 Jan 27 19:15 log`

**Comment by aund** [comment] 2021-01-27 21:41
Hi both,

Thanks for the responses. Just to say I managed to fix this by using the uninstall commands you posted in issues and I then reinstalled as a non root user and frontend working now.

Thanks for your help.

I'll leave open for now in case it doesn't work for KifKick

**Comment by KifKick** [comment] 2021-01-27 22:27
Yeah, fixed with installing as a non root user.

As root:
- `adduser pi`
- `usermod -aG sudo pihole`
- `su pi`
- Now run install script

I still can help to fix installing it as root user.

**Comment by pucherot** [comment] 2021-01-28 05:41
The problem is in installing Pi.Alert with the **root** user.
Doing this, Pi.Alert installs to /root/pialaert

I think this is not a good idea, it is better to install it on a normal user (not superuser), for example pi. 

If you prefer continue using root user, web server needs to have access to **/root/pialaert**. 
In this way you must run these command:
~~~
chmod g+x,o+x /root
~~~

**Closed** 2021-01-28 11:08 UTC
